# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm run build --if-present
    - name: Desplegando front...
     
      run: |
        echo "${{ env.SSH_PRIVATE_KEY }}" > ssh_key
        chmod 600 ssh_key
        sshpass -p '2hdibm144Calvera' ssh -o StrictHostKeyChecking=no diegoCalvera@20.172.149.117 "rm -rf /var/www/hotel-app/*"
        sshpass -p '2hdibm144Calvera' scp -o  StrictHostKeyChecking=no ./dist/hotel-app/* diegoCalvera@20.172.149.117:/var/www/hotel-app/
